# Generated by Django 5.0.6 on 2024-05-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0002_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
