# Generated by Django 5.0.6 on 2024-05-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
