# Generated by Django 5.0.6 on 2024-06-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('email',)},
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='Appointment',
        ),
        migrations.AlterModelTable(
            name='healthhistory',
            table='HealthHistory',
        ),
    ]
