# Generated by Django 5.0.6 on 2024-06-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0010_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
